#!/usr/bin/env bash
#
# Every migration and the seed, concatenated into one file you can paste into a
# Supabase SQL editor.
#
#   ./scripts/db-bundle.sh > supabase/setup.sql
#
# `db-deploy.sh` is the better tool when you have psql and a connection string:
# it applies migrations one at a time, records each one, and can adopt a project
# that already has some of them. This exists for the case that has none of that
# — a brand new project, a browser, and nobody wanting to install Postgres to
# stand one up.
#
# The output is deliberately ONE transaction. Half a schema is worse than none:
# an interrupted paste that leaves `rooms` but no `create_post` produces a site
# that boots, lists rooms, and fails on the first thing anybody types. `begin`
# at the top and `commit` at the bottom means it either all lands or none does.
#
# `create extension citext` is the one statement here that some managed
# platforms refuse inside a transaction. Supabase does not — extensions are
# installed by the `postgres` role the SQL editor already runs as — but if a
# future host complains, that line is the one to pull out and run first.
#
# Regenerating is not optional after adding a migration, and `db-bundle.test.ts`
# fails if the committed file drifts.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

banner() {
  printf '\n\n-- %s\n-- %s\n-- %s\n\n' \
    "$(printf '=%.0s' {1..74})" "$1" "$(printf '=%.0s' {1..74})"
}

cat <<'HEADER'
-- thewall.social — the whole database, in one file.
--
-- Generated by scripts/db-bundle.sh. Do not edit by hand: edit the migration it
-- came from and regenerate, or the next person to run db-deploy.sh gets a
-- different schema from the next person to paste this.
--
-- WHERE TO RUN IT
--   Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
--   It takes a few seconds. There is nothing to fill in.
--
-- WHAT IT DOES
--   Creates every table, function, policy and grant, then seeds nine rooms with
--   posts in them. §5: "an empty room is worse than no room", so a project that
--   comes up bare is not finished.
--
-- SAFE TO RE-RUN? No. This is for a project with nothing in it. Against a
--   project that already has the schema it will fail on the first `create
--   table` and roll the whole thing back, which is the right outcome but not a
--   useful one — use scripts/db-deploy.sh there instead, which applies only
--   what is missing.
--
-- ONE STATEMENT MAY BE REFUSED, and it is worth knowing which. The seed inserts
--   five accounts into `auth.users` so the seeded posts have authors. On some
--   projects that schema is owned by `supabase_auth_admin` and the insert fails
--   with "permission denied for table users". The whole file rolls back if so.
--   The fix is in supabase/seed.sql's own comment: create the five accounts
--   through the Auth admin API and re-run. Everything above the seed is
--   unaffected either way.

begin;
HEADER

for migration in "${root}"/supabase/migrations/*.sql; do
  banner "$(basename "${migration}")"
  cat "${migration}"
  # Migrations do not all end in a semicolon-newline, and concatenation makes
  # that somebody else's problem rather than nobody's.
  printf '\n;\n'
done

banner 'seed.sql — §5, the rooms arrive warm'
cat "${root}/supabase/seed.sql"

cat <<'FOOTER'

-- The bookkeeping table db-deploy.sh keeps, created here so this project is
-- indistinguishable from one deployed that way. Without it the first
-- db-deploy.sh run against this project falls back to adopting it by probing —
-- which works, but only because all eighteen probes happen to be right, and a
-- wrong one re-runs a migration against a schema that already has it.
create table if not exists public.applied_migrations (
  filename   text primary key,
  applied_at timestamptz not null default now()
);
revoke all on public.applied_migrations from public, anon, authenticated;

insert into public.applied_migrations (filename) values
FOOTER

# The same directory db-deploy.sh walks, in the same order — so a migration
# cannot be in the bundle above and missing from this record.
names=()
for migration in "${root}"/supabase/migrations/*.sql; do names+=("$(basename "${migration}")"); done
for i in "${!names[@]}"; do
  printf "  ('%s')%s\n" "${names[i]}" \
    "$([ "${i}" -eq "$(( ${#names[@]} - 1 ))" ] && printf '' || printf ',')"
done

cat <<'FOOTER'
on conflict do nothing;

commit;

-- Every room below should have posts in it. A zero is a seed that did not land.
select r.slug, r.ephemeral, count(p.id) as posts, r.next_post_no as next_address
  from public.rooms r
  left join public.posts p on p.room_slug = r.slug
 group by r.slug, r.ephemeral, r.sort_order, r.next_post_no
 order by r.sort_order;
FOOTER
